version: '3'

services:
  db:
    image: mdillon/postgis
    env_file:
      - env_file

  pgadmin4:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 9090:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=mmaia.cc@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=adminadmin

  flaskapp:
    build: .
    env_file:
      - env_file
    volumes:
      - .:/opt/services/flaskapp/src
    depends_on:
      - db
      - migration

  migration:
    build: .
    command: python migrate.py
    env_file:
      - env_file
    volumes:
      - .:/opt/services/flaskapp/src
    depends_on:
      - db
  nginx:
    image: "nginx:1.13.5"
    ports:
      - "8080:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - flaskapp
