version: '3'
services:
  db:
    image: mdillon/postgis
    env_file:
      - env_file
    networks:
      - db_nw
    ports:
      - "5433:5432"
  flaskapp:
    build: .
    env_file:
      - env_file
    volumes:
      - .:/opt/services/flaskapp/src
    networks:
      - db_nw
      - web_nw
    depends_on:
      - db
      - migration
  migration:
    build: .
    command: python migrate.py
    env_file:
      - env_file
    volumes:
      - .:/opt/services/flaskapp/src
    networks:
      - db_nw
      - web_nw
    depends_on:
      - db
  nginx:
    image: "nginx:1.13.5"
    ports:
      - "8080:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
    networks:
      - web_nw
    depends_on:
      - flaskapp
networks:
  db_nw:
    external:
      name: fila-da-creche-api-db
  web_nw:
    external:
      name: fila-da-creche-api-web
volumes:
  dbdata:
